Repository BrugApp/brug, pull requests merged in 2022-03, with the labels that each got.

#11 Improve README.md
  README.md
Labels: documentation

#42 add home page update
  app/src/androidTest/java/com/github/brugapp/brug/MainActivityTest.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/unlost_logo.xml
  app/src/main/res/mipmap-anydpi-v26/unlost_logo_round.xml
  app/src/main/res/mipmap-hdpi/unlost_logo.png
  app/src/main/res/mipmap-hdpi/unlost_logo_foreground.png
  app/src/main/res/mipmap-hdpi/unlost_logo_round.png
  app/src/main/res/mipmap-mdpi/unlost_logo.png
  app/src/main/res/mipmap-mdpi/unlost_logo_foreground.png
  app/src/main/res/mipmap-mdpi/unlost_logo_round.png
  app/src/main/res/mipmap-xhdpi/unlost_logo.png
  app/src/main/res/mipmap-xhdpi/unlost_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/unlost_logo_round.png
  app/src/main/res/mipmap-xxhdpi/unlost_logo.png
  app/src/main/res/mipmap-xxhdpi/unlost_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/unlost_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/unlost_logo.png
  app/src/main/res/mipmap-xxxhdpi/unlost_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/unlost_logo_round.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/unlost_logo_background.xml
  app/src/main/unlost_logo-playstore.png
Labels: enhancement

#110 Refactor registration activity to UI/ViewModel/Model layers
  app/src/androidTest/java/com/github/brugapp/brug/RegisterUserTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/brugapp/brug/MainActivity.kt
  app/src/main/java/com/github/brugapp/brug/RegisterUser.kt
  app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
  app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
  app/src/main/res/layout/activity_register_user.xml
Labels: estimated: 1h, actual: 2h

#134 Integrate FirebaseInterface in RegisterUserViewModel
  app/src/androidTest/java/com/github/brugapp/brug/FirebaseHelperTest.kt
  app/src/main/java/com/github/brugapp/brug/data/FirebaseHelper.kt
  app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
Labels: estimated: 2h, actual: 2h
